"""Removed first_name, last_name and address columns from users

Revision ID: ca4810b6f5d1
Revises: ea61cd5411a5
Create Date: 2023-05-17 12:30:48.077105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca4810b6f5d1'
down_revision = 'ea61cd5411a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bikes', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'email')
    op.drop_column('bikes', 'year')
    # ### end Alembic commands ###
